task:
  container:
    image: wulan17/archlinux:latest
    cpu: 8
    memory: 24G

  matrix:
    test_script: bash build.sh
    env:
      ci_secret: "ENCRYPTED[9b06d0b1deaac330add9edc41aaf447f61a7a6c28b4e1eeea7951e4c77a28de5f459d92540fde58d44b63b64a1fb0b58]"
